version: '3'
services:
  backend:
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend_container
    tty: true
    volumes:
      - ./backend:/app/backend
    # ports:
    # -
  frontend:
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend_container
    tty: true
    volumes:
      - ./frontend:/app/frontend
    # command: command
    # ports:
    # -
  mysql:
    build:
      context: .
      dockerfile: ./docker/mysql/Dockerfile
    container_name: mysql_container
    # environment:
    #   - name=value
    # volumes:
    #   -
    # ports:
    #   -
